# -*- coding: utf-8 -*-
"""simulate-rabbitWolf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WNWcqcOjNnN0iiq44PBSxzQtA1P_v9q9
"""

import random

def simulate_predator_prey(initial_wolves, initial_rabbits, max_grass=400, grass_growth_rate=5):

    rabbit_food_capacity = 45
    rabbit_metabolism = 3
    rabbit_reproduction_age = 10
    rabbit_reproduction_prob = 0.5
    rabbit_min_food_reproduce = 40
    rabbit_max_age = 25

    wolf_food_capacity = 200
    wolf_metabolism = 2
    wolf_reproduction_age = 10
    wolf_reproduction_prob = 0.5
    wolf_min_food_reproduce = 120
    wolf_max_age = 50


    grass = max_grass
    rabbits = [{'age': 0, 'food': rabbit_food_capacity // 2} for _ in range(initial_rabbits)]
    wolves = [{'age': 0, 'food': wolf_food_capacity // 2} for _ in range(initial_wolves)]

    rounds = 0

    while rabbits and wolves:
        rounds += 1


        grass = min(max_grass, grass + grass_growth_rate)


        for rabbit in rabbits:
            if grass >= 10:
                grass -= 10
                rabbit['food'] = min(rabbit_food_capacity, rabbit['food'] + 10)
            else:
                rabbit['food'] -= rabbit_metabolism


        for wolf in wolves:
            if rabbits:
                rabbit = rabbits.pop()
                wolf['food'] = min(wolf_food_capacity, wolf['food'] + 10)
            else:
                wolf['food'] -= wolf_metabolism

        # เอากระต่ายตายออก
        rabbits = [rabbit for rabbit in rabbits if rabbit['food'] > 0 and rabbit['age'] < rabbit_max_age]

        # เอาหมาป่าตายออก
        wolves = [wolf for wolf in wolves if wolf['food'] > 0 and wolf['age'] < wolf_max_age]


        for rabbit in rabbits:
            rabbit['age'] += 1

        for wolf in wolves:
            wolf['age'] += 1

        # ผสมพันกระต่ายอะ
        new_rabbits = []
        for rabbit in rabbits:
            if rabbit['age'] >= rabbit_reproduction_age and rabbit['food'] >= rabbit_min_food_reproduce:
                if random.random() < rabbit_reproduction_prob:
                    new_rabbits.append({'age': 0, 'food': rabbit_food_capacity // 2})
        rabbits.extend(new_rabbits)

        # ผสมหมา
        new_wolves = []
        for wolf in wolves:
            if wolf['age'] >= wolf_reproduction_age and wolf['food'] >= wolf_min_food_reproduce:
                if random.random() < wolf_reproduction_prob:
                    new_wolves.append({'age': 0, 'food': wolf_food_capacity // 2})
        wolves.extend(new_wolves)


    return rounds, len(wolves), len(rabbits)

rounds, remaining_wolves, remaining_rabbits = simulate_predator_prey(initial_wolves=5, initial_rabbits=20)
print(f"Simulation ended after {rounds} rounds.")
print(f"Remaining wolves: {remaining_wolves}")
print(f"Remaining rabbits: {remaining_rabbits}")